### ISSUE TITLE
Automated checks improvement

### ISSUE THREAD

**Issue by Serzbiedry** [Gilly7CE/Gilly7CE-Carpet-Addons#66]
To prevent issues that occur only when launching game, there should be extra automated check that runs minecraft client and sees if it works correctly.
This is especially prominent with problems in en-us.json file and is importand step to make sure all releases are working correctly.

**Comment by Gilly7CE** [comment]
Running the client might be too much, but at least ensuring the resource file can be read easily. This could be an automated test that is ran.
