### ISSUE TITLE
Add a rule to allow placing blocks to replace flowers like grass.

### ISSUE THREAD

**Issue by DH12043** [Gilly7CE/Gilly7CE-Carpet-Addons#90]
Add a rule to allow placing blocks to replace flowers like grass.
This would preferably just add to or remove from a list of blocks that can be replaced in such a way.
Options: false, all_flowers, one_tall_flowers

**Comment by Gilly7CE** [comment]
Rule name: `replaceableFlowers`

Description: placing blocks on flowers will replace them like grass

**Comment by Gilly7CE** [comment]
As for the options, using an enum would be good. Much like how we already use one for the `movableEmptyEndPortalFrames` rule.
